name: Node.js CI

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test -- --coverage --watchAll=false
      - name: Comment with Test Coverage
        uses: adRise/jest-cov-reporter@main
        with:
          branch-coverage-report-path: ./coverage/coverage-final.json
          base-coverage-report-path: ./coverage/master-coverage-final.json
          delta: 0.3
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          fullCoverageDiff: true
          useSameComment: true


