name: Node.js CI

on:
  pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test --coverage
      - name: TestCoverage
        id: testCoverage
        uses: raulanatol/jest-coverage-comment-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-existing-reports: true

